apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: devops-final
type: Opaque
stringData:
  # Replace with actual RDS endpoint and credentials
  DATABASE_URL: "jdbc:postgresql://rds-endpoint:5432/productdb"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "YourSecurePassword123!"
