# =============================================================================
# BACKEND SERVICE - ProductX Backend
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: productx
  labels:
    app: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
